// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
	"time"
)

const createUser = `
INSERT INTO users (name, dob)
VALUES ($1, $2)
RETURNING id, name, dob
`

func (q *Queries) CreateUser(ctx context.Context, name string, dob time.Time) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name, dob)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const getUser = `SELECT id, name, dob FROM users WHERE id = $1`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const updateUser = `
UPDATE users SET name = $1, dob = $2 WHERE id = $3
RETURNING id, name, dob
`

func (q *Queries) UpdateUser(ctx context.Context, name string, dob time.Time, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, name, dob, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

const deleteUser = `DELETE FROM users WHERE id = $1`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const listUsers = `SELECT id, name, dob FROM users ORDER BY id`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}


const countUsers = `SELECT COUNT(*) FROM users`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	var count int32
	err := q.db.QueryRowContext(ctx, countUsers).Scan(&count)
	return count, err
}

const listUsersPaginated = `
SELECT id, name, dob FROM users ORDER BY id LIMIT $1 OFFSET $2
`

func (q *Queries) ListUsersPaginated(ctx context.Context, limit, offset int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, rows.Err()
}